name: PaRiS 2023
tagline: <br><br>Second Workshop on Personalization and Recommendations in Search (PaRiS)<br>at the WebConf 2023
date: May 1st or 2nd, 2023
analytics: UA-
logo:
  image: static/images/PaRiS.png
  width: 180px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: MiniConf
page_title:
  prefix: 'PaRiS 2023'
  separator: ': '
background_image: static/images/pexels-lacza-4544549.jpg
organization: PaRis Organization Committee

## Remove or change to your chat server.
# chat_server: miniconf.sloppy.zone
# default_presentation_id: 38922815
# default_poster_pdf: /static/images/GLTR_poster.pdf


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
